# Generated by Django 4.0.4 on 2022-06-22 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(default='Please fill in.', max_length=255)),
                ('coming_from', models.CharField(default='Please fill in.', max_length=255)),
                ('to', models.CharField(default='Please fill in.', max_length=255)),
                ('date', models.CharField(default='Please fill in.', max_length=255)),
                ('payment_terms', models.CharField(default='Please fill in.', max_length=255)),
                ('due_date', models.CharField(default='Please fill in.', max_length=255)),
                ('po_number', models.CharField(default='Please fill in.', max_length=255)),
                ('balance_due', models.CharField(default='Please fill in.', max_length=255)),
                ('item', models.CharField(default='Please fill in.', max_length=255)),
                ('rate', models.CharField(default='Please fill in.', max_length=255)),
                ('quantity', models.CharField(default='Please fill in.', max_length=255)),
                ('amount', models.CharField(default='Please fill in.', max_length=255)),
                ('subtotal', models.CharField(default='Please fill in.', max_length=255)),
                ('tax', models.CharField(default='Please fill in.', max_length=255)),
                ('total', models.CharField(default='Please fill in.', max_length=255)),
                ('notes', models.CharField(default='Please fill in.', max_length=255)),
                ('terms', models.CharField(default='Please fill in.', max_length=255)),
            ],
        ),
    ]
